-- LUCID SPACE / LOTTO LAB schema for Supabase PostgreSQL.
-- Run this once in Supabase SQL Editor.

create table if not exists public.lotto_draws (
  draw_number integer primary key check (draw_number > 0),
  draw_date date not null,
  status text not null check (status in ('open', 'completed')),
  number_1 smallint,
  number_2 smallint,
  number_3 smallint,
  number_4 smallint,
  number_5 smallint,
  number_6 smallint,
  completed_at timestamptz
);

create index if not exists idx_lotto_draws_status
  on public.lotto_draws (status, draw_number desc);

create table if not exists public.lotto_predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  draw_number integer not null references public.lotto_draws(draw_number),
  strategy text not null check (strategy in ('random', 'frequency', 'recency', 'balanced', 'lucid')),
  number_1 smallint not null,
  number_2 smallint not null,
  number_3 smallint not null,
  number_4 smallint not null,
  number_5 smallint not null,
  number_6 smallint not null,
  created_at timestamptz not null default now(),
  constraint uq_lotto_prediction unique (user_id, draw_number, strategy)
);

create index if not exists idx_lotto_predictions_draw
  on public.lotto_predictions (draw_number);

create table if not exists public.lotto_results (
  prediction_id bigint primary key references public.lotto_predictions(id) on delete cascade,
  match_count smallint not null check (match_count between 0 and 6),
  checked_at timestamptz not null default now()
);

alter table public.lotto_draws enable row level security;
alter table public.lotto_predictions enable row level security;
alter table public.lotto_results enable row level security;

-- No browser-side table policies are created intentionally.
-- Application data access goes through trusted Next.js server code.
